terraform {
  backend "gcs" {
    bucket = "roleflux-prod-1234-roleflux-tfstate"
    prefix = "terraform/state"
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# 1. Enable Required APIs
resource "google_project_service" "apis" {
  for_each = toset([
    "pubsub.googleapis.com",
    "cloudfunctions.googleapis.com",
    "run.googleapis.com",
    "cloudbuild.googleapis.com",
    "secretmanager.googleapis.com",
    "firestore.googleapis.com",
    "bigquery.googleapis.com",
    "eventarc.googleapis.com",
    "artifactregistry.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "sts.googleapis.com"
  ])
  service            = each.key
  disable_on_destroy = false
}

# 2. Pub/Sub Topic & Dead Letter Queue
resource "google_pubsub_topic" "roleflux_logs" {
  name       = "roleflux-logs-${var.environment}"
  depends_on = [google_project_service.apis]
}

resource "google_pubsub_topic" "roleflux_dlq" {
  name       = "roleflux-logs-dlq-${var.environment}"
  depends_on = [google_project_service.apis]
}

# 3. Log Router Sink
resource "google_logging_project_sink" "roleflux_sink" {
  count                  = var.monitor_org_level ? 0 : 1
  name                   = "roleflux-iam-sink-${var.environment}"
  destination            = "pubsub.googleapis.com/projects/${var.project_id}/topics/${google_pubsub_topic.roleflux_logs.name}"
  filter                 = "protoPayload.methodName=(\"SetIamPolicy\" OR \"storage.setIamPermissions\" OR \"google.iam.admin.v1.CreateServiceAccountKey\")"
  unique_writer_identity = true
}

resource "google_project_iam_binding" "log_writer" {
  count   = var.monitor_org_level ? 0 : 1
  project = var.project_id
  role    = "roles/pubsub.publisher"
  members = [google_logging_project_sink.roleflux_sink[0].writer_identity]
}

# 4. Service Account (Least Privilege)
resource "google_service_account" "roleflux_sa" {
  account_id   = "roleflux-engine-${var.environment}"
  display_name = "RoleFlux Detection Engine SA"
}

resource "google_project_iam_member" "sa_permissions" {
  for_each = toset([
    "roles/bigquery.dataEditor",
    "roles/datastore.user",
    "roles/secretmanager.secretAccessor",
    "roles/aiplatform.user"
  ])
  project = var.project_id
  role    = each.key
  member  = "serviceAccount:${google_service_account.roleflux_sa.email}"
}

# 5. Secret Manager (For Slack Webhook)
resource "google_secret_manager_secret" "slack_webhook" {
  secret_id = "roleflux-slack-webhook-${var.environment}"
  replication {
    auto {}
  }
  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "slack_webhook_val" {
  secret      = google_secret_manager_secret.slack_webhook.id
  secret_data = var.slack_webhook_url
}

# 6. Cloud Function Deployment (Source Code Zip)
data "archive_file" "source" {
  type        = "zip"
  source_dir  = "${path.module}/.."
  output_path = "${path.module}/function-source.zip"
  excludes    = ["terraform", "venv", ".git", "attack-simulator", "tests", ".github", ".gitignore", ".DS_Store", "dashboard"]
}

resource "google_storage_bucket" "source_bucket" {
  name                        = "${var.project_id}-roleflux-src-${var.environment}"
  location                    = var.region
  uniform_bucket_level_access = true
}

resource "google_storage_bucket_object" "archive" {
  name   = "source-${data.archive_file.source.output_md5}.zip"
  bucket = google_storage_bucket.source_bucket.name
  source = data.archive_file.source.output_path
}

# 7. BigQuery Analytics
resource "google_bigquery_dataset" "roleflux_analytics" {
  dataset_id                  = "roleflux_analytics_${var.environment}"
  friendly_name               = "RoleFlux Analytics (${var.environment})"
  description                 = "Stores all findings generated by the RoleFlux Detection Engine"
  location                    = var.region
  default_table_expiration_ms = 31536000000 # 365 days
  depends_on                  = [google_project_service.apis]
}

resource "google_bigquery_table" "findings" {
  dataset_id          = google_bigquery_dataset.roleflux_analytics.dataset_id
  table_id            = "findings"
  deletion_protection = false

  time_partitioning {
    type  = "DAY"
    field = "timestamp"
  }

  schema = <<EOF
[
  {
    "name": "timestamp",
    "type": "TIMESTAMP",
    "mode": "REQUIRED",
    "description": "Time the event occurred"
  },
  {
    "name": "risk_score",
    "type": "INTEGER",
    "mode": "REQUIRED"
  },
  {
    "name": "severity",
    "type": "STRING",
    "mode": "REQUIRED"
  },
  {
    "name": "description",
    "type": "STRING",
    "mode": "REQUIRED"
  },
  {
    "name": "actors",
    "type": "STRING",
    "mode": "REPEATED"
  },
  {
    "name": "targets",
    "type": "STRING",
    "mode": "REPEATED"
  },
  {
    "name": "mitre_techniques",
    "type": "STRING",
    "mode": "REPEATED"
  },
  {
    "name": "raw_event",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "Stringified JSON of the raw audit log"
  }
]
EOF
}

# 8. Cloud Function (2nd Gen)
resource "google_cloudfunctions2_function" "roleflux_engine" {
  name        = "roleflux-engine-${var.environment}"
  location    = var.region
  description = "RoleFlux Deterministic Engine & AI Router"

  build_config {
    runtime     = "python311"
    entry_point = "roleflux_entrypoint" # Matches main.py at root
    source {
      storage_source {
        bucket = google_storage_bucket.source_bucket.name
        object = google_storage_bucket_object.archive.name
      }
    }
  }

  service_config {
    max_instance_count = 10
    available_memory   = "512M"
    timeout_seconds    = 60
    service_account_email = google_service_account.roleflux_sa.email
    # Environment variables
    environment_variables = {
      BIGQUERY_DATASET = google_bigquery_dataset.roleflux_analytics.dataset_id
      BIGQUERY_TABLE   = google_bigquery_table.findings.table_id
    }
    
    # Expose the Secret Manager secret to the Python code as an Environment Variable
    secret_environment_variables {
      key        = "SLACK_WEBHOOK_URL"
      project_id = var.project_id
      secret     = google_secret_manager_secret.slack_webhook.secret_id
      version    = "latest"
    }
  }

  event_trigger {
    trigger_region = var.region
    event_type     = "google.cloud.pubsub.topic.v1.messagePublished"
    pubsub_topic   = google_pubsub_topic.roleflux_logs.id
    retry_policy   = "RETRY_POLICY_DO_NOT_RETRY" # We rely on DLQ instead
  }

  depends_on = [google_project_iam_member.sa_permissions]
}

# 9. Remote State & CI/CD
resource "google_storage_bucket" "terraform_state" {
  name                        = "${var.project_id}-roleflux-tfstate" # Shared state bucket, environments separated by workspace prefix
  location                    = var.region
  force_destroy               = true
  uniform_bucket_level_access = true
  versioning {
    enabled = true
  }
}

# 10. Workload Identity Federation (GitHub Actions)
resource "google_iam_workload_identity_pool" "github_pool" {
  workload_identity_pool_id = "github-actions-pool-${var.environment}"
  display_name              = "GitHub Actions Pool"
  description               = "Identity pool for GitHub Actions CI/CD"
  depends_on                = [google_project_service.apis]
}

resource "google_iam_workload_identity_pool_provider" "github_provider" {
  workload_identity_pool_id          = google_iam_workload_identity_pool.github_pool.workload_identity_pool_id
  workload_identity_pool_provider_id = "github-actions-prov-${var.environment}"
  display_name                       = "GitHub Actions Provider"
  description                        = "OIDC identity pool provider for GitHub Actions"

  attribute_mapping = {
    "google.subject"       = "assertion.sub"
    "attribute.actor"      = "assertion.actor"
    "attribute.repository" = "assertion.repository"
  }

  attribute_condition = "assertion.repository == 'medjahdi/RoleFlux'"

  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com"
  }
}

resource "google_service_account" "github_actions_sa" {
  account_id   = "github-actions-${var.environment}"
  display_name = "GitHub Actions CI/CD Deployer"
}

resource "google_project_iam_member" "github_actions_permissions" {
  for_each = toset([
    "roles/editor",
    "roles/resourcemanager.projectIamAdmin",
    "roles/secretmanager.admin",
    "roles/iam.serviceAccountUser",
    "roles/cloudfunctions.admin",
    "roles/run.admin",
    "roles/artifactregistry.admin"
  ])
  project = var.project_id
  role    = each.key
  member  = "serviceAccount:${google_service_account.github_actions_sa.email}"
}

resource "google_service_account_iam_binding" "workload_identity_user" {
  service_account_id = google_service_account.github_actions_sa.name
  role               = "roles/iam.workloadIdentityUser"
  members = [
    "principalSet://iam.googleapis.com/${google_iam_workload_identity_pool.github_pool.name}/attribute.repository/medjahdi/RoleFlux"
  ]
}
